version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: dbreplicator-rabbitmq
    ports:
      - "5672:5672"   # The standard port your Go app uses to connect
      - "15672:15672" # The web management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  mysql-source:
    image: mysql:8.0
    container_name: mysql-source
    ports:
      - "3306:3306" # Connect locally via port 3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: SourceDB

  mysql-dest:
    image: mysql:8.0
    container_name: mysql-dest
    ports:
      - "3307:3306" # Connect locally via port 3307
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: DestinationDB
